### ISSUE TITLE
After previously launching the modpack multiple days in a row it no longer properly launches.

### ISSUE THREAD

**Issue by heccindragon** [Irgendwer01/Gregtech-Skyblock-Edition#12]
I've played the pack for a number of days and today when launching the game it started to launch but almost immediately failed. I've tried installing it on curseforge rather than on prism but it still fails to launch properly. I'm unsure what to make of the logs so hopefully you can. 

[debug.log](https://github.com/user-attachments/files/17536261/debug.log)

**Comment by dreais** [comment]
hey, known bug wit mod director and chisel
go to your `config/mod-director` folder and remove `chisel-modern.curse.json`

**Comment by Irgendwer01** [comment]
Fixed with 3.1-hotfix
