### ISSUE TITLE
Realgar or Arsenic sorure is missing

### ISSUE THREAD

**Issue by AnkeKatomeky** [Irgendwer01/Gregtech-Skyblock-Edition#18]
Quest 803 (Gallium Arsenide) requires Arsenic Dust, which is obtained by centrifuging Realgar. But there is no recipe in the game for a sieve to collect Realgar. I manually added to the drop list for sifting diorite on the t1 mesh. In the ./config/gregtech/sieve_drops.json file, I added a new entry for Realgar, `"zeolite": {"meshlevel": 1, "chance": 0.01},`. This does the job, but it may cause some unbalance.

**Comment by Irgendwer01** [comment]
Thanks for the report, fixed it in dev as of https://github.com/Irgendwer01/gregtech-skybound/commit/148cea32f42116154edd98927f3c0a12702bc75f. Expect an hotfix to release soon

**Comment by myutin** [comment]
(The hotfix is just a more thorough quest description. 7ff6190 now lists cobaltite as a source of arsenic. The lack of realgar was working as intended.)
