### ISSUE TITLE
Unnecessary grind in earlygame progression

### ISSUE THREAD

**Issue by Dat-Guy** [Irgendwer01/Gregtech-Skyblock-Edition#2]
Copper cannot be obtained through cobblestone, which results in absurdly low rates resulting from needing to sift copper at a low rate (~24% combined) from granite/diorite, themselves which need to be sifted from dirt (~0.15 of a block from each block of dirt), resulting in a prolonged grind to basic automation.

**Comment by Irgendwer01** [comment]
@Dat-Guy I apologize for there being no Questbook or smth yet, but you can let witchwater float to lava and it will generate you randomly granite, diorite, stone and andesite.
