### ISSUE TITLE
Glowstone unavailable until HV

### ISSUE THREAD

**Issue by myutin** [Irgendwer01/Gregtech-Skyblock-Edition#5]
Most of AE2 is accessible in late-LV, except for the terminals (crafted from vibrant quartz glass). Currently, glowstone is only obtained as a macerator byproduct --- there is no sifting recipe for dust.

**Comment by BronsonMagnan** [comment]
Irgendwer, there used to be a route to this through Dust sifting in original Ceu Skyblock 
Dust, steel stiffened mesh
Glowstone 1x2.5%, Blaze Powder 1x3.7%
