### ISSUE TITLE
Use AE2 UEL: Extended

### ISSUE THREAD

**Issue by Micaias32** [Irgendwer01/Gregtech-Skyblock-Edition#6]
For now, ae2 is not acquirable, but when it is, it would be good to use a more powerful version.
UEL: Extended has bigger cells, bigger crafting CPUs, and is a bit better (though it has some bugs).
I don't remember if the modpack has ae2 stuff, but there's also ae2 stuff: extended if it does.
[Mod Link.](https://github.com/beecupbe/ae2uel_extended)

**Comment by Irgendwer01** [comment]
No
